version: '0.14'

services:
  redis:
    container_name: n2rich-redis
    image: redis:7.0.11-alpine
    restart: always

  django:
    container_name: django
    build:
      context: ./n2rich
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./n2rich:/usr/src/app
    ports:
      - 8001:8000
    env_file:
      - .env
    depends_on:
      - redis

  celery_worker:
    container_name: n2rich-celery-worker
    build:
      context: ./n2rich
    command: celery --app=n2rich worker -l INFO
    volumes:
      - ./n2rich:/usr/src/app
    depends_on:
      - redis

  celery_beat:
    container_name: n2rich-celery-beat
    build:
      context: ./n2rich
    command: celery --app=n2rich beat
    volumes:
      - ./n2rich:/usr/src/app
    depends_on:
      - redis

