# Generated by Django 4.2.6 on 2023-11-01 18:22

from django.db import migrations, models
import enrichment.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnrichmentRecordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysed_at', models.DateTimeField(auto_now_add=True)),
                ('enrichment_field', models.CharField(choices=[('Transcription', 'Transcription'), ('Pathways', 'Pathways'), ('Ontologies', 'Ontologies'), ('Diseases/Drugs', 'Diseases/Drugs'), ('Cell Types', 'Cell Types')], max_length=30)),
                ('description', models.CharField(blank=True, help_text='Write a recollective description for enrichment analysis up to 280 character.', max_length=280, null=True)),
                ('gene_list', models.CharField(help_text='Copy your biomarker candidates up to 100 genes.', max_length=500, validators=[enrichment.validators.gene_list_validator])),
                ('email', models.EmailField(blank=True, help_text='Share your e-mail adress to see enrichment results in your email as txt.', max_length=100, null=True)),
            ],
        ),
    ]
