# Generated by Django 4.2.6 on 2023-11-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrichment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrichmentrecordmodel',
            name='enrichment_field',
            field=models.CharField(choices=[('Transcription', 'Transcription'), ('Pathways', 'Pathways'), ('Ontologies', 'Ontologies'), ('Diseases/Drugs', 'Diseases/Drugs'), ('Cell Types', 'Cell Types')], default='Ontologies', max_length=30),
        ),
    ]
