# Generated by Django 4.2.6 on 2023-11-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrichment', '0002_enrichmentrecordmodel_gene_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('contact_at', models.DateTimeField(auto_now_add=True, verbose_name='contact_at')),
                ('email', models.EmailField(max_length=255, verbose_name='email')),
                ('subject', models.CharField(choices=[('general_info', 'General Information'), ('suggestion', 'Suggestion'), ('request_for_support', 'Request for Support'), ('contrib_to_dev', 'Contribute to Development'), ('bug_declaration', 'Bug Declaration'), ('other', 'Other')], default='General Information', max_length=255, verbose_name='subject')),
                ('message', models.TextField(max_length=1024, verbose_name='message')),
            ],
        ),
    ]
